### ISSUE TITLE
hostname and hosts entries not working on CentOS7 w/o NetworkManager

### ISSUE THREAD

**Issue by travisgroth** [GoogleCloudPlatform/compute-image-packages#491]
Unsure if this is also broken in CentOS6 and other derivatives but if you have NetworkManager disabled, the google-compute-engine script installed at /etc/dhcp/dhclient.d/google_hostname.sh does not function correctly.  While /etc/resolv.conf is updated properly, the system hostname, /etc/hosts entries and metadata hosts entries are never installed.  

The root cause appears to be that google_hostname.sh calls /bin/set_hostname without any path:
````
google_hostname_config() {
  set_hostname
}
````
and the redhat network-scripts environment defines a function called set_hostname, which winds up conflicting:
````
 grep set_hostname -R /etc/*
/etc/dhcp/dhclient.d/google_hostname.sh:  /bin/set_hostname
/etc/sysconfig/network-scripts/network-functions:set_hostname ()
/etc/sysconfig/network-scripts/ifup-post:	    set_hostname $HOSTNAME
````

The net result is that google's /bin/set_hostname is never called.  Changing google_hostname.sh to reference set_hostname with a full path fixes the issue.  It might be better to just rename set_hostname to something that is clearly a google specific script, however.

**Comment by illfelder** [comment]
I put together a quick pull request based on your suggestion (#492). I'll take a closer look to determine if it is a valid solution to the problem you encountered.

**Comment by travisgroth** [comment]
@illfelder any word on that change yet?

**Comment by illfelder** [comment]
Apologies for the delay - we've merged the PR into development so (if all goes well) it should be part of our next release.

**Comment by illfelder** [comment]
This fix is in the latest release.

**Comment by ronlipke** [comment]
I know this issue is closed and it is working for us in the current 2.7.1 version w/o NetworkManager on Centos7, but I'm still not sure why it was working *with* NetworkManager enabled.  Wouldn't it be calling the same dhclient script?

Been scratching my head on this for a bit.

**Comment by zmarano** [comment]
NetworkManager still uses dhclient, and the package copies the dhcp hook to the right place for the default NetworkManager managed client: https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/specs/google-compute-engine.spec#L87

**Comment by ronlipke** [comment]
Thanks for the response!  
And you are correct, but the older version (2.3.5) I'm using, has the conflicting `set_hostname` in `/etc/dhcp/dhclient.d/google_hostname.sh` without any path.  
```
google_hostname_config() {
  set_hostname
}
```
Our instance boots off an image with NetworkManager disabled and never updates it's hostname to the instance name in GCE even after performing a network restart (the original problem in this issue). 

```
$ hostnamectl --static
packer-59b00191-5a8f-bd3f-8f28-f8f85d68a1b3
$ sudo systemctl restart network
$ hostnamectl --static
packer-59b00191-5a8f-bd3f-8f28-f8f85d68a1b3
```
However, after enabling and starting NetworkManager and then performing a network restart, hostname updates correctly to the instance name.
```
$ sudo systemctl enable NetworkManager && sudo systemctl restart NetworkManager
Created symlink from /etc/systemd/system/ {...}
$ sudo systemctl restart network && hostnamectl --static
tk-worker-gci-kubernetes-worker-50175c
```

Updating to the current google-compute-engine version of 2.7.1 does fix the issue, but my nagging curiosity is still trying to figure out why with NetworkManager enabled the hostname updates correctly when it should still be using the `/etc/dhcp/dhclient.d/google_hostname.sh` script 😆
Unless there is some other magic happening within NetworkManager?

**Comment by travisgroth** [comment]
@ronlipke see my original problem report.

>and the redhat network-scripts environment defines a function called set_hostname, which winds up conflicting

That conflicting function isn't declared when executed from NetworkManager.

**Comment by ronlipke** [comment]
Ah, that's the part I was missing.  Thanks a bunch @travisgroth.
